<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Compile Update="src\Forms\DashboardForm.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="src\Forms\RegistrationForm.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="src\PenTestToolkit\NetworkScanning\NetworkScannerForm.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="src\PenTestToolkit\NetworkScanning\SSHScannerForm.cs">
      <SubType>Form</SubType>
    </Compile>
  </ItemGroup>

</Project>