<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Compile Update="src\Classes\PremiumUser\FullScanHistoryForm.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="src\Classes\PremiumUser\CompareResultsForm.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="src\Classes\PremiumUser\AnalyticsDashboardForm.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="src\Classes\PremiumUser\SavedConfigsForm.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="src\Classes\PremiumUser\ScheduledScansForm.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="src\Classes\PremiumUser\PremiumUserForm.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="src\Classes\RegularUser\RegularUserForm.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="src\Classes\Toolmanager\ToolManagerForm.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="src\Classes\Viewer\ReportViewerForm.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="src\Classes\Viewer\ViewerForm.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="src\Forms\DashboardForm.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="src\Forms\RegistrationForm.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="src\PenTestToolkit\NetworkScanning\SSHScannerForm.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="src\PenTestToolkit\NetworkScanning\NetworkScannerForm.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="src\PenTestToolkit\NetworkScanning\NetworkScannerForm.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="src\PenTestToolkit\NetworkScanning\SSHScannerForm.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="src\PenTestToolkit\WebPentest\WebSecurityAuditForm.cs" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="src\Classes\Admin\" />
  </ItemGroup>

</Project>